version: 2.1
executors:
    php-executor:
        docker:
            - image: circleci/php:7.2-zts-node-browsers
        working_directory: ~/repo
    node-executor:
        docker:
            -   image: circleci/node:10
        working_directory: ~/repo
jobs:
  dependencies:
        executor: php-executor
        steps:
            - checkout
            - run:
                  name: Download Dependencies
                  command: composer install -n --prefer-dist
            - persist_to_workspace:
                root: .
                paths: .
  test:
      executor: php-executor
      steps:
          - checkout
          -   run:
                  name: Download Dependencies
                  command: composer install -n --prefer-dist
          -   persist_to_workspace:
                  root: .
                  paths: .
  build:
    executor: php-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  publish_release:
      executor: node-executor
      steps:
          - attach_workspace:
                at: .
          - run:
                name: Publish release
                command: npx semantic-release
workflows:
    version: 2
    test_build_tag:
        jobs:
            - dependencies
            - test:
                  requires:
                      - dependencies

